/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/sequentTheme.ts
 * Command: astryx theme build src/theme/sequentTheme.ts --out src/theme/sequent.css
 * Generated: 2026-07-04T16:48:00.522Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Heading' {
  interface XDSHeadingLevelMap {
    '1': true;
    '2': true;
    '3': true;
    '4': true;
    '5': true;
    '6': true;
  }
}
