/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/sequentTheme.ts
 * Command: astryx theme build src/theme/sequentTheme.ts --out src/theme/sequent.css
 * Generated: 2026-07-04T16:48:00.520Z
 */

import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const sequentTheme: DefinedTheme;
